/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as WorldsIndexRouteImport } from './routes/worlds.index'
import { Route as WorldsSlugRouteImport } from './routes/worlds.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldsIndexRoute = WorldsIndexRouteImport.update({
  id: '/worlds/',
  path: '/worlds/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldsSlugRoute = WorldsSlugRouteImport.update({
  id: '/worlds/$slug',
  path: '/worlds/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/stories': typeof StoriesRoute
  '/worlds/$slug': typeof WorldsSlugRoute
  '/worlds/': typeof WorldsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/stories': typeof StoriesRoute
  '/worlds/$slug': typeof WorldsSlugRoute
  '/worlds': typeof WorldsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/stories': typeof StoriesRoute
  '/worlds/$slug': typeof WorldsSlugRoute
  '/worlds/': typeof WorldsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/stories' | '/worlds/$slug' | '/worlds/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/stories' | '/worlds/$slug' | '/worlds'
  id: '__root__' | '/' | '/about' | '/stories' | '/worlds/$slug' | '/worlds/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  StoriesRoute: typeof StoriesRoute
  WorldsSlugRoute: typeof WorldsSlugRoute
  WorldsIndexRoute: typeof WorldsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worlds/': {
      id: '/worlds/'
      path: '/worlds'
      fullPath: '/worlds/'
      preLoaderRoute: typeof WorldsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worlds/$slug': {
      id: '/worlds/$slug'
      path: '/worlds/$slug'
      fullPath: '/worlds/$slug'
      preLoaderRoute: typeof WorldsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  StoriesRoute: StoriesRoute,
  WorldsSlugRoute: WorldsSlugRoute,
  WorldsIndexRoute: WorldsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
